name: Dependency Update

on:
  schedule:
    - cron: '0 2 * * 1' # Weekly on Monday at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Update dependencies
        run: |
          echo "Updating dependencies..."
          npm update
          echo "Dependencies updated, creating PR..."

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet package-lock.json; then
            echo "has-changes=false" >> $GITHUB_OUTPUT
            echo "No dependency updates available"
          else
            echo "has-changes=true" >> $GITHUB_OUTPUT
            echo "Dependencies have been updated"
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has-changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            ## Dependency Updates

            This PR contains automated dependency updates.

            ### Changes
            - Updated npm dependencies to latest compatible versions
            - Updated package-lock.json

            ### Testing
            - [ ] CI tests pass
            - [ ] Manual testing completed

            Auto-generated by GitHub Actions
          branch: maintenance/dependency-update-${{ github.run_number }}
          delete-branch: true

      - name: No updates needed
        if: steps.changes.outputs.has-changes == 'false'
        run: echo "✅ All dependencies are up to date"
